# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
export TERM=xterm-256color

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="nolen"

# For messing with bpython...mostly for fun
temp_pythonpath_change() {
    oldpath=$PYTHONPATH
    export PYTHONPATH=/home/nolen/code/repos/bpython:${PYTHONPATH}
    bpython
    export PYTHONPATH=$oldpath
}
alias bpp='temp_pythonpath_change'

# No more annoying pushd messages...
#setopt PUSHD_SILENT

# Blank pushd goes to home
setopt PUSHD_TO_HOME

# protect against crazy rm...
setopt RM_STAR_WAIT

#try to stop those really annoying corrections...
alias sudo='nocorrect sudo'

source $HOME/.dotfiles_config
alias vv='vim ~/.vimrc'
alias zz='vim ~/.zshrc'
alias pp='vim ~/.pentadactylrc'
alias au='ps au'
alias aux='ps aux'
alias rel='source ~/.zshrc'
alias a='cd'
alias bp='bpython'
#alias emacs='emacs -nw'
alias code='cd ~/code'
alias etp='cd ~/code/etp'
alias dotf='cd ~/code/dotfiles'
alias down='cd ~/Downloads/'
alias jj='cd ~/code/assorted'
alias sshe='ssh nroyalty@sandnet.emergingthreats.net'
alias sshec='ssh -Y nroyalty@sandnet.emergingthreats.net'
alias sshef='ssh -L 127.0.0.1:3306:172.30.130.124:3306 nroyalty@sandnet.emergingthreats.net'
alias sshi='ssh nroyalty@burrow.cs.indiana.edu'
alias so='cd ~/code/stackoverflow/'
#ctrl-delete to forward kill word
bindkey "[3;5~" kill-word

#git aliases
alias ga='git add'
alias gp='git push'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gpu='git pull'
alias gcl='git clone'
alias gr='git rm'
alias gmv='git mv'

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git, github, brew, osx, perl, pip, python, ssh-agent)
#plugins=(git, github, brew, osx, perl, pip, python)
#plugins=(git, osx, pip, python)
plugins=(git, osx, pip, python, brew)

#for paths
source $HOME/.profile
source $ZSH/oh-my-zsh.sh

# Customize to your needs...

#export PERL_LOCAL_LIB_ROOT="$HOME/perl5";
#export PERL_MB_OPT="--install_base /home/nolen/perl5";
#export PERL_MM_OPT="INSTALL_BASE=/home/nolen/perl5";
#export PERL5LIB="/home/nolen/perl5/lib/perl5/i686-linux-gnu-thread-multi-64int:/home/nolen/perl5/lib/perl5";
#export PATH="/home/nolen/perl5/bin:$PATH";
