# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
export TERM=xterm-256color

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="nolen"

# No more annoying pushd messages...
#setopt PUSHD_SILENT

# Blank pushd goes to home
setopt PUSHD_TO_HOME

# protect against crazy rm...
setopt RM_STAR_WAIT

#try to stop those really annoying corrections...
alias sudo='nocorrect sudo'

source $HOME/.dotfiles_config
alias vv='vim ~/.vimrc'
alias zz='vim ~/.zshrc'
alias pp='vim ~/.pentadactylrc'
alias au='ps au'
alias aux='ps aux'
alias rel='source ~/.zshrc'
alias a='cd'
alias bp='bpython'
#alias emacs='emacs -nw'
alias code='cd $CODEDIR'
alias etp='cd $CODEDIR/etp'
alias dotf='cd $CODEDIR/dotfiles'
alias down='cd ~/Downloads/'
#ctrl-delete to forward kill word
bindkey "[3;5~" kill-word

#sometimes, you just gotta use ed
alias ed='ed -p:'

cl() { cd ~/class/"$*"; }

#git aliases
alias ga='git add'
alias gp='git push'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gpu='git pull'
alias gcl='git clone'
alias gr='git rm'
alias gmv='git mv'

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git, osx, pip, python, brew)

#for paths
source $HOME/.profile
source $ZSH/oh-my-zsh.sh

# Customize to your needs...

#export PERL_LOCAL_LIB_ROOT="$HOME/perl5";
#export PERL_MB_OPT="--install_base /home/nolen/perl5";
#export PERL_MM_OPT="INSTALL_BASE=/home/nolen/perl5";
export RPROMPT="%{$fg[green]%}%@%{$reset_color%}"
