# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
export TERM=xterm-256color
#if [[ ${TERM} == "screen-bce" || ${TERM} == "screen" ]]; then
    #export TERM=screen-256color-bce
  #function preexec()
  #{
                ##echo -ne "\ek${1%% *}\e\\"
  #}
#else
    #echo -n `clear`
#fi

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="nolen"

foreground-vi() {
    fg %vi
}
zle -N foreground-vi
bindkey '' foreground-vi

temp_pythonpath_change() {
    oldpath=$PYTHONPATH      
    export PYTHONPATH=/home/nolen/code/repos/bpython:${PYTHONPATH}
    bpython
    export PYTHONPATH=$oldpath
}
alias bpp='temp_pythonpath_change'

# No more annoying pushd messages...
#setopt PUSHD_SILENT

# Blank pushd goes to home
setopt PUSHD_TO_HOME

# protect against crazy rm...
setopt RM_STAR_WAIT

source $HOME/.dotfiles_config
#alias vim='vim.gnome'
alias vv='vim ~/.vimrc'
alias zz='vim ~/.zshrc'
alias pp='vim ~/.pentadactylrc'
alias rel='source ~/.zshrc'
alias a='cd'
alias bp='bpython'
alias emacs='emacs -nw'
#alias code='cd $CODEDIR'
alias code='cd ~/code'
#alias etp='cd $CODEDIR/etp'
alias etp='cd ~/code/etp'
#alias dotf='cd $CODEDIR/dotfiles'
alias dotf='cd ~/code/dotfiles'
alias down='cd ~/Downloads/'
#alias 
#alias sshe='ssh nroyalty@sandnet.emergingthreats.net'
alias sshe='ssh -Y nroyalty@sandnet.emergingthreats.net'
#alias sshef='ssh -Y -L 3306:localhost:3306 nroyalty@sandnet.emergingthreats.net'
alias sshef='ssh -L 127.0.0.1:3306:172.30.130.124:3306 nroyalty@sandnet.emergingthreats.net'
#alias sshef='ssh -L 3306:localhost:3306 nroyalty@sandnet.emergingthreats.net'
#ctrl-delete to forward kill word
bindkey "[3;5~" kill-word

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git, github, brew, osx, perl, pip, python, ssh-agent)
#plugins=(git, github, brew, osx, perl, pip, python)
plugins=(git, osx, pip, python)

source $HOME/.profile
source $ZSH/oh-my-zsh.sh

# Customize to your needs...

export PERL_LOCAL_LIB_ROOT="/home/nolen/perl5";
export PERL_MB_OPT="--install_base /home/nolen/perl5";
export PERL_MM_OPT="INSTALL_BASE=/home/nolen/perl5";
export PERL5LIB="/home/nolen/perl5/lib/perl5/i686-linux-gnu-thread-multi-64int:/home/nolen/perl5/lib/perl5";
export PATH="/home/nolen/perl5/bin:$PATH";
