#!/bin/bash
alias bp='bpython'

if ls -F --color=auto >&/dev/null ; then
    alias ls='ls -F --color=auto'
else
    if ls -F -G >&/dev/null ; then
        alias ls='ls -F -G'
    fi
fi

alias rel='. ~/.bash_profile'

alias vv='vim ~/.vimrc'
alias vbp='vim ~/.bash_profile'
alias vbr='vim ~/.bashrc'
alias vba='vim ~/.bash_aliases'
alias vpp='vim ~/.profile'
