# Source dotfiles_config early because of weird local machine settings.
if [ -e $HOME/.dotfiles_config ]; then
    source $HOME/.dotfiles_config
fi

source $HOME/.zsh/settings.zsh
source $HOME/.zsh/functions.zsh
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/paths.zsh

# Not nearly as butchered as my current vim theme
ZSH_THEME="nolen"

# Autoupdate is annoying.
DISABLE_AUTO_UPDATE="true"

# It's nice to know how your title is being set
#DISABLE_AUTO_TITLE="true"

# oh-my-zsh plugins to use (~/.oh-my-zsh/plugins/)
# NOT COMMA SEPARATED LOL
plugins=(pip python brew extract git golang svn)

# Make oh-my-zsh work.
# the ZSH variable is used by various omz scripts
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh
source $HOME/.dotfiles_config

source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh
chruby ruby-3.1.3 # run chruby to see actual version

## >>> conda initialize >>>
## !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
    #eval "$__conda_setup"
#else
    #if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        #. "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    #else
        #export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
    #fi
#fi
#unset __conda_setup
## <<< conda initialize <<<

