# Source dotfiles_config early because of weird local machine settings.
if [ -e $HOME/.dotfiles_config ]; then
    source $HOME/.dotfiles_config
fi

source $HOME/.zsh/settings.zsh
source $HOME/.zsh/functions.zsh
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/paths.zsh

# Not nearly as butchered as my current vim theme
ZSH_THEME="nolen"

# Autoupdate is annoying.
DISABLE_AUTO_UPDATE="true"

# It's nice to know how your title is being set
DISABLE_AUTO_TITLE="true"

# oh-my-zsh plugins to use (~/.oh-my-zsh/plugins/)
# NOT COMMA SEPARATED LOL
plugins=(pip python brew extract mercurial svn)

# Make oh-my-zsh work.
# the ZSH variable is used by various omz scripts
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh
