"-----------------------------------------------------------------------------
"Settings to run first
"-----------------------------------------------------------------------------
"Run settings that throw a fit if they aren't run first.  That means calling
"all the plugins I installed via pathogen, turning on filetype stuff + syntax,
"setting my mapleader, and using my (heavily modified) jellybeans colorscheme
call pathogen#infect()
filetype on
filetype plugin indent on
syntax enable
let mapleader = ";"
colorscheme jellybeans

"-----------------------------------------------------------------------------
"Works in progress
"-----------------------------------------------------------------------------
map <Leader><Leader>m :call CheckMapping()<Cr>

nnoremap <Leader><C-l> <C-l>:set nohlsearch<Cr>

map <Leader>h :he 
map <Leader>H :he<Cr><C-w>c

"-----------------------------------------------------------------------------
"Mappings
"-----------------------------------------------------------------------------
"emacs-style hotkeys for command line
cno <C-a> <Home>
cno <C-e> <End>
cno <C-b> <Left>
cno <C-f> <Right>
cno <C-n> <Down>
cno <C-p> <Up>

"some weirder alt-based hotkeys for commandline as well
cno f <C-Right>
cno b <C-Left>
cno a <Home>
cno e <End>
cno  <End><C-u>

"I try to use ctrl-c so that I can use escape based hotkeys in insert mode
ino f <C-Right>
ino b <C-Left>
ino a <Home>
ino e <End>
ino  

"c-j/k for up/down, c-h/l for start/end of line
map <C-j> 15j
map <C-k> 15k
map <C-h> ^
map <C-l> $

"make tab work how I would except
nmap <tab> v>><esc>
nmap <S-tab> v<<<esc>
vmap <tab> >gv
vmap <S-tab> <gv

"z[h]igh z[l]ow z[m]id
nmap zh z<Cr>
map zm z.
nmap zl zb

"Q to play macro q
map Q @q

"ways to write files quickly(or as sudo). ZZ has to be rebound because
"minibufexplr can be really really dumb sometimes
map <Leader>w :w<Cr>:echo "Written"<Cr>
map <Leader>W :w !sudo tee %
nmap ZZ :wqa<Cr>

"Buffer tricks,c-n/p for navigating, ;` for last buffer
map <Leader>` :b#<Cr>
map <C-n> :bn<Cr>
map <C-p> :bp<Cr>

"Comment keys, ;j to comment out line, ;J to uncomment, ;c-d to make a
"commented copy of a line(so I'm not afraid to break it)
map <Leader>j ;cc
map <Leader>J ;cu
map <Leader><C-d> Ypk<Leader>cc
vmap <Leader><C-d> ygvA<Esc>pgv;jgvA<Esc>j

"leader e to open a new file(has trailing space so you can start typing the
"filename right away)
map <Leader>e :e 

"vv to open vimrc, vc-v to open vimrc in vertical split, rr to reload vimrc
map <Leader>vv :e ~/.vimrc<Cr>
map <Leader>v<C-v> <C-w>v<C-w>l:e ~/.vimrc<Cr>
map <Leader>rr :source ~/.vimrc<Cr>
map <Leader><Leader>r :source ~/.vimrc<Cr>

"c-\ to toggle highlight search
map <C-\> :set hlsearch! hlsearch?<Cr>

"Generate filename for datetime, add extension if possible, write to
"codedir/tmp if it exists
function! GenerateTmpFilename()
    let ftypedict = {"python": "py", "vim": "vim", "perl": "pl", "sh": "sh", "zsh": "zsh"}
    return strftime("%m-%d-%y__%H:%M:%S").".".get(ftypedict, &filetype, "tmp")
endfunction

map <Leader><C-w> :r ~/.dotfiles_config<Cr>0df=v$d:w <C-r>"/tmp/<C-r>=GenerateTmpFilename()<Cr><Cr>

"allows you to search stack overflow from vim
imap <C-x><C-h> <C-o>:call StackoverflowQuery()<Cr>
nnoremap <Leader><C-h> :call StackoverflowQuery()<Cr>

"-----------------------------------------------------------------------------
"Settings
"-----------------------------------------------------------------------------
set tabstop=8                           " Tabs are 8 spaces but act like they're 4
set softtabstop=4
set shiftwidth=4                        " autoindent uses 4 spaces
set expandtab                           " expand tabs to proper number of spaces
set shiftround                          " round expanded tabs to multiples of shiftwidth
set listchars=tab:\ \ ,trail:·          " show tabs and trailing spaces visually
set wrap                                " Lines are wrapped instead of hidden
set linebreak                           " lines are wrapped at (decently) good points
set list                                " show tabs
set backspace=indent,eol,start          " backspace is able to kill indents, line breaks, and pre-insert
set shortmess=atI                       " Attempt to prevent annoying multiline prompts
set showcmd                             " show commands as they are typed
set ruler                               " show absolute position in bottom right
set relativenumber                      " linenumbers relative to current position
set numberwidth=3                       " don't allocate too much space for numbers
set timeoutlen=2000                     " 2 seconds to complete commands
set scrolloff=2                         " give cursor breathing room at top and bottom of screen
set nocompatible                        " not compatible with vi
set incsearch                           " find searches as you type
set ignorecase                          " ignore case for searches...
set smartcase                           " unless capital letters are used
set gdefault                            " default to global search and replace, /g to disable
set complete-=i                         " don't bother with imports when doing tab completion
set wildmenu                            " enable enhanced tab complete
set ofu=syntaxcomplete#Complete         " enable omnifunc completion
set pumheight=10                        " no more than 10 items at a time in insert mode completion
set completeopt=menuone,longest,preview
set virtualedit=onemore                 " allow cursor to move 1 character past end of line

"-----------------------------------------------------------------------------
"Minor extension stuff
"-----------------------------------------------------------------------------
let g:miniBufExplorerMoreThanOne = 1
let g:pydiction_location = '~/.vim/vimfiles/ftplugin/pydiction/complete-dict'
"because tagbar and minubufexplorer can be *really* annoying together
function! ToggleOggleOoo()
    TagbarToggle
    let buf = bufname("%")
    if buf == "-MiniBufExplorer-"
        wincmd j
    elseif buf == "__Tagbar__"
        wincmd h| wincmd j| wincmd l| wincmd l
        TagbarSetFoldlevel 1
        exe 'norm! 2j'
    endif
endfunction
map <silent> <Leader><C-t> :call ToggleOggleOoo()<Cr>
let g:tagbar_compact = 1| let g:tagbar_autofocus = 1

"-----------------------------------------------------------------------------
"Autocommands
"-----------------------------------------------------------------------------
"takes care of how autocomplete menus should appear and disappear
au CursorMovedI * if pumvisible() == 0|pclose|endif
au InsertLeave * if pumvisible() == 0|pclose|endif

au BufNewFile *.pl 0r ~/.vim/skeleton/skeleton.pl
au BufNewFile *.py 0r ~/.vim/skeleton/skeleton.py

"-----------------------------------------------------------------------------
"Misc
"-----------------------------------------------------------------------------
"Attemp to make a few things look nicer, primarily because I am always using a
"transparent background.  My jellybeans colorscheme is also heavily
"customized/pillaged
hi clear Pmenu
hi Pmenu term=bold ctermfg=81 ctermbg=darkgrey guifg=Cyan

"Matchparen always confused me because I couldn't tell where my cursor was and
"which paren was highlighted.  I try to fix this by using a ridiculous purple color
hi clear MatchParen
hi MatchParen ctermbg=90

"This marks special characters like the  one for escape in cyan instead of
"using a nearly invisible color
hi clear SpecialKey
hi SpecialKey ctermfg=81 guifg=Cyan

hi Statement ctermfg=31
hi Comment ctermfg=245

hi Todo ctermfg=red
