"-----------------------------------------------------------------------------
" Settings that cause problems if they aren't run first
"-----------------------------------------------------------------------------
set nocompatible          " Don't try to be compatible with vi
call pathogen#infect()    " Tell pathogen to enable bundle plugins
filetype plugin indent on " Enable filetype detection, as well as ftplugins and filetype indenting
syntax enable             " Yes please syntax highlighting
let mapleader = ";"       " Set mapleader to ; and use \ for ;'s functionality
nnoremap \ ;
colorscheme jellybeans    " Use a super butchered, heavily modified jellybeans colorscheme

"-----------------------------------------------------------------------------
" Mappings
"-----------------------------------------------------------------------------
"c-j/k for vertical movement, c-h/l for start/end of line
map <C-j> 15j
map <C-k> 15k
map <C-h> ^
map <C-l> $

"use tab in normal and visual mode to indent text
nmap <Tab> v>><Esc>
nmap <S-Tab> v<<<Esc>
vmap <Tab> >gv
vmap <S-Tab> <gv

"toggles: <F7> spell check, <F8> pylint, ;s hlsearch, ;<C-f> flash cursor line
map <F7>          :set spell! spell?<Cr>
map <F8>          :Pylint<Cr>:redraw!<Cr>
map <Leader>s     :set hlsearch! hlsearch?<Cr>
map <Leader><C-f> :set cursorline<Cr>:sleep 250m<Cr>:set nocursorline<Cr>

"General purpose mappings. ;d black hole deletes, ZZ writes all and exits, Q plays macro q, gQ is annoying so don't use it
nnoremap <silent> <Leader>d "_d
vnoremap <silent> <Leader>d "_d
map ZZ :wqa<Cr>
map Q @q
map gQ <Nop>

";w write file, ;W sudo write file, ;e edit file, ;E edit file in current dir
map <Leader>w :w<Cr>:echo "Written"<Cr>
map <Leader>W :w !sudo tee % >/dev/null
map <Leader>e :e 
map <Leader>E :e <C-r>=expand('%:p:h').'/'<Cr>

"Switch buffers with c-n/p, kill buffer with <Leader>D
map <C-n> :bn<Cr>
map <C-p> :bp<Cr>
map <Leader>D :TagbarClose<Cr>:bd<Cr>

"Comment keys, ;j to comment out line, ;J to uncomment, ;c-d copy current line(s) and comment them out(for use as a backup)
map <Leader>j <Leader>cc
map <Leader>J <Leader>cu
nmap <Leader><C-d> Ypk<Leader>cc
vmap <Leader><C-d> ygvA<Esc>pgv<Leader>ccgvA<Esc>j

"vv to open vimrc, R to reload vimrc
map <Leader>vv :e ~/.vimrc<Cr>
map <Leader>R  :source ~/.vimrc<Cr>:echo "Refreshed"<Cr>

"ctrl c sends an escape, instead of messing up things like visual column insert
inoremap <C-c> <Esc>
vnoremap <C-c> <Esc>

"Mapings for functions in plugin/generalFunctions.vim and other personal plugins
map <Leader>N     :call RenameFile()<Cr>
map <Leader>nt    :call TempFile()<Cr>
map <Leader><C-t> :call ToggleOggleOoo()<Cr>

"-----------------------------------------------------------------------------
"Settings
"-----------------------------------------------------------------------------
set tabstop=8                           " Tabs are 8 spaces
set softtabstop=4                       " Tabs act like they are 4 spaces
set shiftwidth=4                        " autoindent uses 4 spaces
set expandtab                           " expand tabs to proper number of spaces
set shiftround                          " round expanded tabs to multiples of shiftwidth
set listchars=tab:\ \ ,trail:·          " show tabs and trailing spaces visually
set wrap                                " Lines are wrapped instead of hidden
set linebreak                           " lines are wrapped at (decently) good points
set textwidth=0                         " Prevent ftplugins from causing vim to do obnoxious autowrapping
set list                                " show tabs
set backspace=indent,eol,start          " backspace is able to kill indents, line breaks, and pre-insert
set shortmess=atI                       " Attempt to prevent annoying multiline prompts
set showcmd                             " show commands as they are typed
set ruler                               " show absolute position in bottom right
set relativenumber                      " linenumbers relative to current position
set numberwidth=2                       " don't allocate too much space for numbers(don't need much since I use relativenumber)
set scrolloff=2                         " give cursor breathing room at top and bottom of screen
set incsearch                           " find searches as you type
set ignorecase                          " ignore case for searches
set smartcase                           " stop ignoring case for searches if capital letters are used
set gdefault                            " default to global search and replace, /g to disable
set complete-=i                         " don't bother with imports when doing tab completion
set wildmenu                            " enable enhanced tab complete
set ofu=syntaxcomplete#Complete         " enable omnifunc completion
set pumheight=10                        " no more than 10 items at a time in insert mode completion
set completeopt=menuone,longest,preview " insert completion: use popup menu(even for 1 match), only insert longest common text, show extra info about current completion
set virtualedit=onemore                 " allow cursor to move 1 character past end of line
set hidden                              " This allows you to switch to a new buffer without writing your current one
set history=1000                        " Save a lot of history
set undolevels=1000                     " Save a lot of undos as well
set undoreload=10000                    " Reload a bunch of undolevels
set undodir=~/.vim/undodir              " For persistent undo
set undofile                            " Also enables persistent undo(undo between sessions)
set pastetoggle=<C-F7>                  " toggle pastemode with ctrl-F7

"-----------------------------------------------------------------------------
" Minor extension stuff
"-----------------------------------------------------------------------------
let g:Tb_MoreThanOne = 1
let g:pydiction_location = '~/.vim/vimfiles/ftplugin/pydiction/complete-dict'

"-----------------------------------------------------------------------------
" Tagbar stuff
"-----------------------------------------------------------------------------
let g:tagbar_compact     = 1  " no need to waste tagbar space, compact mode is better
let g:tagbar_autofocus   = 1  " autofocus tagbar upon opening it
let g:tagbar_width       = 32 " slightly reduce tagbar width for more screen real estate

"-----------------------------------------------------------------------------
"Misc
"-----------------------------------------------------------------------------
"Matchparen tends to confuse me because I can't tell where my cursor is.  This looks ridiculous but seems to work pretty well
hi clear MatchParen
hi MatchParen ctermfg=126

"This marks special characters like the  one for escape in cyan instead of using a nearly invisible color
hi clear SpecialKey
hi SpecialKey ctermfg=81 guifg=Cyan

hi Statement ctermfg=31
hi Comment ctermfg=245
hi Todo ctermfg=yellow

hi clear CursorLine
hi CursorLine cterm=NONE,reverse
